---
- name: restart webserver
  service:
    name: "{{ apache2_http_name }}"
    state: restarted

- name: reload webserver
  service:
    name: "{{ apache2_http_name }}"
    state: reloaded

- name: restart supervisor
  service:
    name: supervisor
    state: restarted
